### ISSUE TITLE
Package breaks stacktraces

### ISSUE THREAD

**Issue by KristofferC** [SciML/TruncatedStacktraces.jl#18]
```
julia> @snoopr using DiffEqBase
7913-element Vector{Any}:
Error showing value of type Vector{Any}:
ERROR: UndefVarError: `isinplace` not defined

Some of the types have been truncated in the stacktrace for improved reading. To emit complete information
in the stack trace, evaluate `TruncatedStacktraces.VERBOSE[] = true` and re-run the code.

Stacktrace:
  [1] show(io::IOContext{IOBuffer}, t::
SYSTEM (REPL): showing an error caused an error
```

Honestly, this is just BS. Do you guys hate people trying to improve the SciML ecosystem?

**Comment by thomvet** [comment]
Apart from the whole invalidation issue, is it possible that some of the defined show(…) methods are simply bugged (using variables that are not defined)?

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/TruncatedStacktraces.jl/pull/19 adds safety to the macro in the non-verbose case, same as https://github.com/SciML/SciMLBase.jl/pull/419. https://github.com/SciML/TruncatedStacktraces.jl/pull/20 now states everything should use the macro to avoid any bugged show methods. And a preference exists to remove all of the invalidations.
